import * as core from '@actions/core';
import * as github from '@actions/github';
import * as exec from '@actions/exec';
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';
import { scanArchitecture } from './scanner';
import { evaluateRules, ArchitectureRule } from './rules';
import { diffGraphs } from './differ';
import { generateMermaid } from './mermaid';

async function run(): Promise<void> {
  try {
    const token = core.getInput('github-token', { required: true });
    const rulesFile = core.getInput('rules-file') || '.driftgraph.yml';
    
    const octokit = github.getOctokit(token);
    const context = github.context;

    if (context.eventName !== 'pull_request') {
      core.info('Not a pull request event. Skipping Driftgraph.');
      return;
    }

    const pr = context.payload.pull_request;
    if (!pr) {
      throw new Error('Pull request payload is missing');
    }

    const baseSha = pr.base.sha;
    const baseRef = pr.base.ref;
    
    core.info(`Base ref: ${baseRef}, SHA: ${baseSha}`);

    const baseDir = path.resolve('/tmp/driftgraph-base');
    const headDir = process.cwd();

    core.info(`Checking out base branch into ${baseDir}...`);
    try {
      if (fs.existsSync(baseDir)) {
        fs.rmSync(baseDir, { recursive: true, force: true });
      }
      await exec.exec('git', ['fetch', 'origin', baseRef]);
      await exec.exec('git', ['worktree', 'add', baseDir, 'FETCH_HEAD']);
    } catch (error) {
      core.warning(`Failed to checkout base branch via worktree: ${error}. Visualizer might compare against empty graph.`);
    }

    let rules: ArchitectureRule[] = [];
    const rulesPath = path.resolve(headDir, rulesFile);
    if (fs.existsSync(rulesPath)) {
      core.info(`Found rules file at ${rulesPath}`);
      const content = fs.readFileSync(rulesPath, 'utf8');
      if (rulesPath.endsWith('.json')) {
        rules = JSON.parse(content);
      } else {
        rules = yaml.parse(content);
      }
    } else {
      core.info(`No rules file found at ${rulesPath}. Gatekeeping skipped.`);
    }

    const tsconfigBase = fs.existsSync(path.join(baseDir, 'tsconfig.json')) ? path.join(baseDir, 'tsconfig.json') : undefined;
    const tsconfigHead = fs.existsSync(path.join(headDir, 'tsconfig.json')) ? path.join(headDir, 'tsconfig.json') : undefined;

    core.info('Scanning base architecture...');
    const baseGraph = fs.existsSync(baseDir) ? scanArchitecture(baseDir, tsconfigBase) : { nodes: [], edges: [] };
    
    core.info('Scanning head architecture...');
    const headGraph = scanArchitecture(headDir, tsconfigHead);

    core.info('Evaluating architecture rules...');
    const violations = evaluateRules(headGraph, rules);

    core.info('Diffing graphs...');
    const diff = diffGraphs(baseGraph, headGraph, violations);

    core.info('Generating Mermaid.js diagram...');
    const mermaidDiagram = generateMermaid(diff);

    const commentBody = `
## 🏗️ Driftgraph Architecture Report

Here is the visual diff of the architectural changes in this PR:

\`\`\`mermaid
${mermaidDiagram}
\`\`\`

${violations.length > 0 ? `\n> ❌ **Architecture Violations Detected (${violations.length})**\n> Please check the highlighted red edges in the diagram.\n` : '\n> ✅ **No architecture violations detected.**\n'}

*Generated by [Driftgraph](https://github.com/your-org/driftgraph) 🕵️‍♂️*
`;

    const { owner, repo } = context.repo;
    const issue_number = pr.number;

    core.info('Fetching existing comments...');
    const { data: comments } = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number,
    });

    const existingComment = comments.find(c => c.body?.includes('Driftgraph Architecture Report'));

    if (existingComment) {
      core.info('Updating existing comment...');
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingComment.id,
        body: commentBody,
      });
    } else {
      core.info('Creating new comment...');
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number,
        body: commentBody,
      });
    }

    if (violations.length > 0) {
      core.setFailed(`Architecture rules violated! ${violations.length} forbidden dependencies found.`);
    }

  } catch (error) {
    if (error instanceof Error) core.setFailed(error.message);
  }
}

run();
